name: HW5 Testrunner

on: push

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies and set up test files
      run: |
        sudo apt-get install -y sqlite3
        pip install -r requirements.txt
        tar -xzvf flights-small.tar.gz
    - name: Run tests
      run: |
        python3 grading.py
